import Foundation
import SwiftUI

// MARK: - Curriculum
//
// All content is bilingual EN/DE via String Catalog (Localizable.xcstrings).
// Math expressions use the {var:x}{sup:^2} syntax from MathText.

enum Curriculum {

    // MARK: - Pre-Algebra

    static let preAlgFractions = Lesson(
        id: "pre.frac",
        title: "Fractions",
        intro: "Add, subtract, and simplify common fractions.",
        formulas: [
            Formula(key: "pre.frac.f1",
                    name: "Common denominator",
                    math: "{var:a}/{var:b} + {var:c}/{var:d} = ({var:a}{var:d} + {var:b}{var:c}) / ({var:b}{var:d})",
                    explanation: "Multiply across to share a denominator, then add the tops."),
            Formula(key: "pre.frac.f2",
                    name: "Simplify",
                    math: "({var:a}·{var:k}) / ({var:b}·{var:k}) = {var:a}/{var:b}",
                    explanation: "Divide numerator and denominator by their common factor."),
        ],
        questions: [
            Question(id: "pre.frac.q1",
                     prompt: "Compute 1/2 + 1/3. Give the simplest fraction.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["5/6"]),
                     hint: "Common denominator is 6.",
                     solutionSteps: ["1/2 = 3/6", "1/3 = 2/6", "Sum: 5/6"]),
            Question(id: "pre.frac.q2",
                     prompt: "Simplify 8/12.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["2/3"]),
                     hint: "Both share a factor of 4.",
                     solutionSteps: ["GCD(8,12) = 4", "8/12 = 2/3"]),
            Question(id: "pre.frac.q3",
                     prompt: "Which is larger?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "3/4", math: nil),
                        .init(label: "5/8", math: nil),
                        .init(label: "They are equal", math: nil),
                     ], correctIndex: 0),
                     hint: "Convert to a common denominator.",
                     solutionSteps: ["3/4 = 6/8", "6/8 > 5/8"]),
            Question(id: "pre.frac.q4",
                     prompt: "Compute 2/3 − 1/6.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["1/2", "3/6"]),
                     hint: "Use 6 as the denominator.",
                     solutionSteps: ["2/3 = 4/6", "4/6 − 1/6 = 3/6 = 1/2"]),
            Question(id: "pre.frac.q5",
                     prompt: "True or false: 2/4 + 1/2 = 1.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Simplify 2/4 first.",
                     solutionSteps: ["2/4 = 1/2", "1/2 + 1/2 = 1"]),
        ]
    )

    static let preAlgPercents = Lesson(
        id: "pre.pct",
        title: "Percentages",
        intro: "Percentages are fractions out of 100.",
        formulas: [
            Formula(key: "pre.pct.f1",
                    name: "Percent of",
                    math: "{var:p}%  of  {var:x}  =  ({var:p}/100) · {var:x}",
                    explanation: "Convert to a fraction, then multiply."),
            Formula(key: "pre.pct.f2",
                    name: "Increase / decrease",
                    math: "new = old · (1 ± {var:p}/100)",
                    explanation: "+ for increase, − for decrease."),
        ],
        questions: [
            Question(id: "pre.pct.q1",
                     prompt: "What is 20% of 80?",
                     math: nil,
                     kind: .freeAnswer(accepted: ["16"]),
                     hint: "20/100 = 0.2.",
                     solutionSteps: ["0.2 · 80 = 16"]),
            Question(id: "pre.pct.q2",
                     prompt: "A jacket costs $80 and is 25% off. What's the sale price?",
                     math: nil,
                     kind: .freeAnswer(accepted: ["60"]),
                     hint: "Multiply by 0.75.",
                     solutionSteps: ["80 · 0.75 = 60"]),
            Question(id: "pre.pct.q3",
                     prompt: "If a price goes up by 10%, then down by 10%, the result is:",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "The original price", math: nil),
                        .init(label: "1% lower", math: nil),
                        .init(label: "1% higher", math: nil),
                        .init(label: "Depends on the price", math: nil),
                     ], correctIndex: 1),
                     hint: "Apply 1.10 then 0.90.",
                     solutionSteps: ["1.10 · 0.90 = 0.99", "= 1% lower than original"]),
            Question(id: "pre.pct.q4",
                     prompt: "15 is what percent of 60?",
                     math: nil,
                     kind: .freeAnswer(accepted: ["25", "25%"]),
                     hint: "15/60.",
                     solutionSteps: ["15/60 = 0.25 = 25%"]),
            Question(id: "pre.pct.q5",
                     prompt: "True or false: 200% of 5 equals 10.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "200% = 2.",
                     solutionSteps: ["2 · 5 = 10"]),
        ]
    )

    static let preAlgOrder = Lesson(
        id: "pre.order",
        title: "Order of Operations",
        intro: "PEMDAS — parentheses, exponents, multiplication/division, addition/subtraction.",
        formulas: [
            Formula(key: "pre.order.f1",
                    name: "Order",
                    math: "1) (  )    2) {sup:^n}    3) · ÷    4) + −",
                    explanation: "Left-to-right inside the same level."),
        ],
        questions: [
            Question(id: "pre.order.q1",
                     prompt: "Compute 3 + 4 · 2.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["11"]),
                     hint: "Multiplication before addition.",
                     solutionSteps: ["4 · 2 = 8", "3 + 8 = 11"]),
            Question(id: "pre.order.q2",
                     prompt: "Compute (3 + 4) · 2.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["14"]),
                     hint: "Parentheses first.",
                     solutionSteps: ["3 + 4 = 7", "7 · 2 = 14"]),
            Question(id: "pre.order.q3",
                     prompt: "Compute 2³ − 2 · 3.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["2"]),
                     hint: "Exponent, then multiplication, then subtraction.",
                     solutionSteps: ["2³ = 8", "2 · 3 = 6", "8 − 6 = 2"]),
            Question(id: "pre.order.q4",
                     prompt: "Compute 12 ÷ 4 + 2.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["5"]),
                     hint: "Division before addition.",
                     solutionSteps: ["12 ÷ 4 = 3", "3 + 2 = 5"]),
            Question(id: "pre.order.q5",
                     prompt: "Which equals 17?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "5 + 3 · 4", math: nil),
                        .init(label: "(5 + 3) · 4", math: nil),
                        .init(label: "20 − 4 + 1", math: nil),
                        .init(label: "2 · 3 + 5", math: nil),
                     ], correctIndex: 0),
                     hint: "Multiply before adding.",
                     solutionSteps: ["5 + 12 = 17"]),
        ]
    )

    // MARK: - Algebra

    static let linearEquations = Lesson(
        id: "alg.linear",
        title: "Linear Equations",
        intro: "Solve for the unknown by isolating it on one side.",
        formulas: [
            Formula(key: "alg.linear.f1",
                    name: "Inverse operations",
                    math: "{var:x} + {var:a} = {var:b}  ⟹  {var:x} = {var:b} − {var:a}",
                    explanation: "Whatever you do to one side, do to the other."),
            Formula(key: "alg.linear.f2",
                    name: "Two-step rule",
                    math: "{var:a}{var:x} + {var:b} = {var:c}  ⟹  {var:x} = ({var:c} − {var:b}) / {var:a}",
                    explanation: "Undo addition first, then division."),
        ],
        questions: [
            Question(id: "alg.linear.q1",
                     prompt: "Solve for x:", math: "2{var:x} + 6 = 14",
                     kind: .freeAnswer(accepted: ["4"]),
                     hint: "Subtract 6 from both sides, then divide by 2.",
                     solutionSteps: ["Subtract 6: 2x = 8", "Divide by 2: x = 4"]),
            Question(id: "alg.linear.q2",
                     prompt: "Solve for x:", math: "5{var:x} − 3 = 2{var:x} + 9",
                     kind: .freeAnswer(accepted: ["4"]),
                     hint: "Move all x to one side first.",
                     solutionSteps: ["Subtract 2x: 3x − 3 = 9", "Add 3: 3x = 12", "Divide by 3: x = 4"]),
            Question(id: "alg.linear.q3",
                     prompt: "Which value of x satisfies 3(x − 2) = 9?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "x = 1", math: nil),
                        .init(label: "x = 3", math: nil),
                        .init(label: "x = 5", math: nil),
                        .init(label: "x = 7", math: nil),
                     ], correctIndex: 2),
                     hint: "Distribute first: 3x − 6 = 9.",
                     solutionSteps: ["3x − 6 = 9", "3x = 15", "x = 5"]),
            Question(id: "alg.linear.q4",
                     prompt: "Solve: 7 = x + 4.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["3"]),
                     hint: "Subtract 4 from both sides.",
                     solutionSteps: ["x = 7 − 4 = 3"]),
            Question(id: "alg.linear.q5",
                     prompt: "Solve: −2x + 8 = 0.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["4"]),
                     hint: "Move 8 over, then divide.",
                     solutionSteps: ["−2x = −8", "x = 4"]),
        ]
    )

    static let quadratics = Lesson(
        id: "alg.quad",
        title: "Quadratic Formula",
        intro: "Every quadratic ax² + bx + c = 0 has solutions you can read off the formula.",
        formulas: [
            Formula(key: "alg.quad.f1",
                    name: "Quadratic formula",
                    math: "{var:x} = (−{var:b} ± √({var:b}{sup:^2} − 4{var:a}{var:c})) / (2{var:a})",
                    explanation: "Use it whenever factoring is awkward."),
            Formula(key: "alg.quad.f2",
                    name: "Discriminant",
                    math: "Δ = {var:b}{sup:^2} − 4{var:a}{var:c}",
                    explanation: "Δ > 0 → two real roots. Δ = 0 → one. Δ < 0 → none in ℝ."),
        ],
        questions: [
            Question(id: "alg.quad.q1",
                     prompt: "Solve x² − 5x + 6 = 0. Give both roots, comma-separated, smallest first.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["2,3", "2, 3"]),
                     hint: "Look for two numbers that multiply to 6 and add to −5.",
                     solutionSteps: ["Factor: (x − 2)(x − 3) = 0", "Roots: x = 2 or x = 3"]),
            Question(id: "alg.quad.q2",
                     prompt: "How many real solutions does x² + 4x + 5 = 0 have?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "Zero", math: nil),
                        .init(label: "One", math: nil),
                        .init(label: "Two", math: nil),
                        .init(label: "Infinite", math: nil),
                     ], correctIndex: 0),
                     hint: "Compute the discriminant.",
                     solutionSteps: ["Δ = 16 − 20 = −4", "Δ < 0 → no real solutions"]),
            Question(id: "alg.quad.q3",
                     prompt: "Solve x² − 9 = 0. Smallest first, comma-separated.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["-3,3", "-3, 3"]),
                     hint: "Difference of squares.",
                     solutionSteps: ["x² = 9", "x = ±3"]),
            Question(id: "alg.quad.q4",
                     prompt: "What's the discriminant of 2x² + 3x − 5?",
                     math: nil,
                     kind: .freeAnswer(accepted: ["49"]),
                     hint: "Δ = b² − 4ac.",
                     solutionSteps: ["Δ = 9 − 4·2·(−5) = 9 + 40 = 49"]),
            Question(id: "alg.quad.q5",
                     prompt: "Solve: x² + x − 6 = 0. Smallest first.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["-3,2", "-3, 2"]),
                     hint: "Factor.",
                     solutionSteps: ["(x + 3)(x − 2) = 0", "x = −3 or x = 2"]),
        ]
    )

    static let exponents = Lesson(
        id: "alg.exp",
        title: "Exponent Rules",
        intro: "Exponents follow tidy rules — once you know them, big powers shrink fast.",
        formulas: [
            Formula(key: "alg.exp.f1",
                    name: "Product",
                    math: "{var:a}{sup:^m} · {var:a}{sup:^n} = {var:a}{sup:^m+n}",
                    explanation: "Same base → add the exponents."),
            Formula(key: "alg.exp.f2",
                    name: "Quotient",
                    math: "{var:a}{sup:^m} / {var:a}{sup:^n} = {var:a}{sup:^m-n}",
                    explanation: "Same base → subtract the exponents."),
            Formula(key: "alg.exp.f3",
                    name: "Power",
                    math: "({var:a}{sup:^m}){sup:^n} = {var:a}{sup:^m·n}",
                    explanation: "Multiply exponents."),
            Formula(key: "alg.exp.f4",
                    name: "Negative",
                    math: "{var:a}{sup:^-n} = 1 / {var:a}{sup:^n}",
                    explanation: "A negative exponent flips the base."),
        ],
        questions: [
            Question(id: "alg.exp.q1",
                     prompt: "Simplify 2³ · 2⁴.", math: nil,
                     kind: .freeAnswer(accepted: ["128", "2^7"]),
                     hint: "Add exponents.",
                     solutionSteps: ["2³⁺⁴ = 2⁷ = 128"]),
            Question(id: "alg.exp.q2",
                     prompt: "Simplify (3²)³.", math: nil,
                     kind: .freeAnswer(accepted: ["729", "3^6"]),
                     hint: "Multiply exponents.",
                     solutionSteps: ["3²·³ = 3⁶ = 729"]),
            Question(id: "alg.exp.q3",
                     prompt: "What is 5⁻²?", math: nil,
                     kind: .freeAnswer(accepted: ["1/25", "0.04"]),
                     hint: "Negative exponent → reciprocal.",
                     solutionSteps: ["5⁻² = 1/5² = 1/25"]),
            Question(id: "alg.exp.q4",
                     prompt: "Simplify x⁵ / x².", math: nil,
                     kind: .freeAnswer(accepted: ["x^3", "x³"]),
                     hint: "Subtract exponents.",
                     solutionSteps: ["x⁵⁻² = x³"]),
            Question(id: "alg.exp.q5",
                     prompt: "True or false: a⁰ = 1 for any nonzero a.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Definition of zero exponent.",
                     solutionSteps: ["By convention, any nonzero base to the 0 is 1."]),
        ]
    )

    static let logarithms = Lesson(
        id: "alg.log",
        title: "Logarithms",
        intro: "A logarithm is the inverse of an exponent — it asks 'what power gives this number?'",
        formulas: [
            Formula(key: "alg.log.f1",
                    name: "Definition",
                    math: "log{sub:_b}({var:x}) = {var:y}  ⇔  {var:b}{sup:^y} = {var:x}",
                    explanation: "Logarithm = the exponent you raise the base by."),
            Formula(key: "alg.log.f2",
                    name: "Product rule",
                    math: "log{sub:_b}({var:x}·{var:y}) = log{sub:_b}({var:x}) + log{sub:_b}({var:y})",
                    explanation: "Multiplying inputs becomes adding outputs."),
            Formula(key: "alg.log.f3",
                    name: "Quotient rule",
                    math: "log{sub:_b}({var:x}/{var:y}) = log{sub:_b}({var:x}) − log{sub:_b}({var:y})",
                    explanation: "Dividing inputs becomes subtracting outputs."),
            Formula(key: "alg.log.f4",
                    name: "Power rule",
                    math: "log{sub:_b}({var:x}{sup:^n}) = {var:n}·log{sub:_b}({var:x})",
                    explanation: "Exponents inside come out as multipliers."),
        ],
        questions: [
            Question(id: "alg.log.q1",
                     prompt: "What is log₂(8)?",
                     math: nil,
                     kind: .freeAnswer(accepted: ["3"]),
                     hint: "Ask: 2 to what power equals 8?",
                     solutionSteps: ["2³ = 8", "So log₂(8) = 3."]),
            Question(id: "alg.log.q2",
                     prompt: "What is log₁₀(1000)?",
                     math: nil,
                     kind: .freeAnswer(accepted: ["3"]),
                     hint: "Powers of 10.",
                     solutionSteps: ["10³ = 1000", "log₁₀(1000) = 3."]),
            Question(id: "alg.log.q3",
                     prompt: "Simplify log(50) + log(2). (Common log, base 10.)",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "1",   math: nil),
                        .init(label: "2",   math: nil),
                        .init(label: "log(52)", math: nil),
                        .init(label: "log(100) = 2 — wait, let me think", math: nil),
                     ], correctIndex: 1),
                     hint: "Product rule turns + into multiplication inside.",
                     solutionSteps: [
                        "log(50) + log(2) = log(50·2)",
                        "= log(100) = 2.",
                     ]),
            Question(id: "alg.log.q4",
                     prompt: "Solve for x: log₃(x) = 4.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["81"]),
                     hint: "Rewrite in exponential form.",
                     solutionSteps: ["log₃(x) = 4 ⇔ 3⁴ = x", "x = 81."]),
            Question(id: "alg.log.q5",
                     prompt: "True or false: log₂(1) = 0.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Any base to the 0 power is 1.",
                     solutionSteps: ["b⁰ = 1 for any nonzero base", "So log_b(1) = 0."]),
        ]
    )

    // MARK: - Calculus

    static let limits = Lesson(
        id: "calc.lim",
        title: "Limits",
        intro: "A limit is the value a function approaches as the input approaches a point.",
        formulas: [
            Formula(key: "calc.lim.f1",
                    name: "Direct substitution",
                    math: "lim {var:x}→{var:a} {var:f}({var:x}) = {var:f}({var:a})",
                    explanation: "Works when f is continuous at a."),
            Formula(key: "calc.lim.f2",
                    name: "Famous limit",
                    math: "lim {var:x}→0  sin {var:x} / {var:x} = 1",
                    explanation: "Useful in trigonometric limits."),
        ],
        questions: [
            Question(id: "calc.lim.q1",
                     prompt: "Find lim x→2 (3x + 1).",
                     math: nil,
                     kind: .freeAnswer(accepted: ["7"]),
                     hint: "Plug 2 in.",
                     solutionSteps: ["3·2 + 1 = 7"]),
            Question(id: "calc.lim.q2",
                     prompt: "Find lim x→0 (x² + 5).",
                     math: nil,
                     kind: .freeAnswer(accepted: ["5"]),
                     hint: "Substitute x = 0.",
                     solutionSteps: ["0 + 5 = 5"]),
            Question(id: "calc.lim.q3",
                     prompt: "What is lim x→0 sin(x)/x?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "0", math: nil),
                        .init(label: "1", math: nil),
                        .init(label: "Undefined", math: nil),
                        .init(label: "x", math: nil),
                     ], correctIndex: 1),
                     hint: "It's the famous limit.",
                     solutionSteps: ["lim x→0 sin(x)/x = 1"]),
            Question(id: "calc.lim.q4",
                     prompt: "True or false: lim x→3 (x² − 9)/(x − 3) = 6.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Factor numerator: (x−3)(x+3).",
                     solutionSteps: ["(x−3)(x+3)/(x−3) = x+3", "At x→3: 6"]),
            Question(id: "calc.lim.q5",
                     prompt: "Find lim x→∞ 1/x.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["0"]),
                     hint: "What does 1/x do as x grows?",
                     solutionSteps: ["1/x → 0 as x → ∞"]),
        ]
    )

    static let derivatives = Lesson(
        id: "calc.deriv",
        title: "Derivatives",
        intro: "The derivative measures how fast something changes.",
        formulas: [
            Formula(key: "calc.deriv.f1",
                    name: "Power rule",
                    math: "d/dx ({var:x}{sup:^n}) = {var:n}{var:x}{sup:^n−1}",
                    explanation: "Bring down the exponent, subtract one."),
            Formula(key: "calc.deriv.f2",
                    name: "Constant rule",
                    math: "d/dx ({var:c}) = 0",
                    explanation: "Constants don't change."),
            Formula(key: "calc.deriv.f3",
                    name: "Sum rule",
                    math: "({var:f} + {var:g}){sup:^′} = {var:f}{sup:^′} + {var:g}{sup:^′}",
                    explanation: "Differentiate term by term."),
            Formula(key: "calc.deriv.f4",
                    name: "Chain rule",
                    math: "d/dx {var:f}({var:g}({var:x})) = {var:f}{sup:^′}({var:g}) · {var:g}{sup:^′}({var:x})",
                    explanation: "Outer derivative times inner derivative."),
        ],
        questions: [
            Question(id: "calc.deriv.q1",
                     prompt: "Find the derivative of 3x² + 2x − 7.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["6x+2", "6x + 2", "2+6x"]),
                     hint: "Power rule on each term; the constant vanishes.",
                     solutionSteps: ["d/dx(3x²) = 6x", "d/dx(2x) = 2", "d/dx(−7) = 0", "Sum: 6x + 2"]),
            Question(id: "calc.deriv.q2",
                     prompt: "What is the slope of f(x) = x³ at x = 2?",
                     math: nil,
                     kind: .freeAnswer(accepted: ["12"]),
                     hint: "f′(x) = 3x², then plug in 2.",
                     solutionSteps: ["f′(x) = 3x²", "f′(2) = 12"]),
            Question(id: "calc.deriv.q3",
                     prompt: "Which is the derivative of 5x⁴?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "20x³", math: nil),
                        .init(label: "5x³", math: nil),
                        .init(label: "4x⁵", math: nil),
                        .init(label: "x³", math: nil),
                     ], correctIndex: 0),
                     hint: "Multiply by the exponent, drop it by one.",
                     solutionSteps: ["5 · 4 · x³ = 20x³"]),
            Question(id: "calc.deriv.q4",
                     prompt: "Differentiate (2x + 1)³. Use the chain rule.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["6(2x+1)^2", "6(2x+1)²"]),
                     hint: "Outer 3·u² times inner 2.",
                     solutionSteps: ["d/du(u³) = 3u²", "Inner u′ = 2", "Product: 3(2x+1)² · 2 = 6(2x+1)²"]),
            Question(id: "calc.deriv.q5",
                     prompt: "True or false: d/dx (sin x) = cos x.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Standard derivative.",
                     solutionSteps: ["This is one of the basic trig derivatives."]),
        ]
    )

    static let integrals = Lesson(
        id: "calc.int",
        title: "Indefinite Integrals",
        intro: "Integration is the reverse of differentiation.",
        formulas: [
            Formula(key: "calc.int.f1",
                    name: "Power rule (integral)",
                    math: "∫ {var:x}{sup:^n} d{var:x} = {var:x}{sup:^n+1}/({var:n}+1) + {var:C}  ({var:n} ≠ −1)",
                    explanation: "Add 1 to the exponent, divide by the new exponent, add C."),
            Formula(key: "calc.int.f2",
                    name: "Constant multiple",
                    math: "∫ {var:k}·{var:f}({var:x}) d{var:x} = {var:k} ∫ {var:f}({var:x}) d{var:x}",
                    explanation: "Constants slide outside the integral."),
            Formula(key: "calc.int.f3",
                    name: "Trig basics",
                    math: "∫ cos {var:x}  d{var:x} = sin {var:x} + {var:C}",
                    explanation: "Reverse of d/dx(sin x) = cos x."),
        ],
        questions: [
            Question(id: "calc.int.q1",
                     prompt: "Compute ∫ 2x dx. Use C for the constant.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["x^2+c", "x²+c", "x^2 + c"]),
                     hint: "Power rule.",
                     solutionSteps: ["∫ 2x dx = 2 · x²/2 + C", "= x² + C"]),
            Question(id: "calc.int.q2",
                     prompt: "Evaluate ∫ (−1) dx.",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "−x + C", math: nil),
                        .init(label: "−1 + C", math: nil),
                        .init(label: "x + C", math: nil),
                        .init(label: "0", math: nil),
                     ], correctIndex: 0),
                     hint: "Treat −1 as a constant, integrate w.r.t. x.",
                     solutionSteps: ["∫ (−1) dx = −x + C"]),
            Question(id: "calc.int.q3",
                     prompt: "Compute ∫ x³ dx.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["x^4/4+c", "x⁴/4+c"]),
                     hint: "Power rule: x^4/4 + C.",
                     solutionSteps: ["∫ x³ dx = x⁴/4 + C"]),
            Question(id: "calc.int.q4",
                     prompt: "Compute ∫ 5 dx.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["5x+c", "5x + c"]),
                     hint: "Constant integrates to constant·x.",
                     solutionSteps: ["∫ 5 dx = 5x + C"]),
            Question(id: "calc.int.q5",
                     prompt: "Find ∫ cos x dx.",
                     math: nil,
                     kind: .freeAnswer(accepted: ["sinx+c", "sin(x)+c", "sin x + c"]),
                     hint: "Reverse of d/dx(sin x).",
                     solutionSteps: ["∫ cos x dx = sin x + C"]),
        ]
    )

    // MARK: - Geometry

    static let pythagoras = Lesson(
        id: "geo.pyth",
        title: "Pythagorean Theorem",
        intro: "In a right triangle, the squared hypotenuse equals the sum of the squared legs.",
        formulas: [
            Formula(key: "geo.pyth.f1",
                    name: "Theorem",
                    math: "{var:a}{sup:^2} + {var:b}{sup:^2} = {var:c}{sup:^2}",
                    explanation: "c is the side opposite the right angle."),
        ],
        questions: [
            Question(id: "geo.pyth.q1",
                     prompt: "A right triangle has legs 3 and 4. Find the hypotenuse.",
                     math: nil, kind: .freeAnswer(accepted: ["5"]),
                     hint: "Square the legs, add, take the root.",
                     solutionSteps: ["3² + 4² = 25", "c = √25 = 5"]),
            Question(id: "geo.pyth.q2",
                     prompt: "Hypotenuse is 13, one leg is 5. The other leg is:",
                     math: nil, kind: .freeAnswer(accepted: ["12"]),
                     hint: "b² = c² − a²",
                     solutionSteps: ["13² − 5² = 169 − 25 = 144", "b = 12"]),
            Question(id: "geo.pyth.q3",
                     prompt: "Legs 6 and 8. Hypotenuse?",
                     math: nil, kind: .freeAnswer(accepted: ["10"]),
                     hint: "Multiply both by 2: 3-4-5 triple.",
                     solutionSteps: ["6² + 8² = 100", "c = 10"]),
            Question(id: "geo.pyth.q4",
                     prompt: "Is 5-12-13 a right triangle?",
                     math: nil, kind: .trueFalse(answer: true),
                     hint: "Check 5² + 12² = 13².",
                     solutionSteps: ["25 + 144 = 169 = 13²"]),
            Question(id: "geo.pyth.q5",
                     prompt: "Diagonal of a square with side 1?",
                     math: nil, kind: .freeAnswer(accepted: ["sqrt(2)", "√2"]),
                     hint: "1² + 1² = 2.",
                     solutionSteps: ["d² = 2", "d = √2"]),
        ]
    )

    static let circles = Lesson(
        id: "geo.circle",
        title: "Circles",
        intro: "π connects a circle's circumference and area to its radius.",
        formulas: [
            Formula(key: "geo.circle.f1",
                    name: "Circumference",
                    math: "{var:C} = 2π{var:r}",
                    explanation: "Distance around the circle."),
            Formula(key: "geo.circle.f2",
                    name: "Area",
                    math: "{var:A} = π{var:r}{sup:^2}",
                    explanation: "How much surface the circle covers."),
        ],
        questions: [
            Question(id: "geo.circle.q1",
                     prompt: "Circumference of a circle with radius 5? In terms of π.",
                     math: nil, kind: .freeAnswer(accepted: ["10pi", "10π", "10*pi"]),
                     hint: "C = 2πr.",
                     solutionSteps: ["C = 2π·5 = 10π"]),
            Question(id: "geo.circle.q2",
                     prompt: "Area of a circle with radius 3? In terms of π.",
                     math: nil, kind: .freeAnswer(accepted: ["9pi", "9π"]),
                     hint: "A = πr².",
                     solutionSteps: ["A = π·9 = 9π"]),
            Question(id: "geo.circle.q3",
                     prompt: "If the diameter is 8, the radius is:",
                     math: nil, kind: .freeAnswer(accepted: ["4"]),
                     hint: "Half of the diameter.",
                     solutionSteps: ["r = d/2 = 4"]),
            Question(id: "geo.circle.q4",
                     prompt: "Doubling the radius makes the area:",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "Double", math: nil),
                        .init(label: "Triple", math: nil),
                        .init(label: "Four times", math: nil),
                        .init(label: "Sixteen times", math: nil),
                     ], correctIndex: 2),
                     hint: "Area scales with r².",
                     solutionSteps: ["(2r)² = 4r²", "Area is 4× larger."]),
            Question(id: "geo.circle.q5",
                     prompt: "True or false: π is approximately 3.14.",
                     math: nil, kind: .trueFalse(answer: true),
                     hint: "Common approximation.",
                     solutionSteps: ["π ≈ 3.14159…"]),
        ]
    )

    static let trianglesArea = Lesson(
        id: "geo.tri",
        title: "Triangle Area",
        intro: "Half base times height.",
        formulas: [
            Formula(key: "geo.tri.f1",
                    name: "Standard",
                    math: "{var:A} = (1/2)·{var:b}·{var:h}",
                    explanation: "Base and height must be perpendicular."),
            Formula(key: "geo.tri.f2",
                    name: "Heron's formula",
                    math: "{var:A} = √({var:s}({var:s}−{var:a})({var:s}−{var:b})({var:s}−{var:c}))",
                    explanation: "s = (a+b+c)/2 is the semi-perimeter."),
        ],
        questions: [
            Question(id: "geo.tri.q1",
                     prompt: "Triangle with base 10 and height 6. Area?",
                     math: nil, kind: .freeAnswer(accepted: ["30"]),
                     hint: "Half base times height.",
                     solutionSteps: ["A = ½ · 10 · 6 = 30"]),
            Question(id: "geo.tri.q2",
                     prompt: "Equilateral triangle with side 2. Area?",
                     math: nil, kind: .freeAnswer(accepted: ["sqrt(3)", "√3"]),
                     hint: "Use side²·√3/4.",
                     solutionSteps: ["A = 2²·√3/4 = √3"]),
            Question(id: "geo.tri.q3",
                     prompt: "If base doubles and height stays the same, area:",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "Stays the same", math: nil),
                        .init(label: "Doubles", math: nil),
                        .init(label: "Quadruples", math: nil),
                        .init(label: "Halves", math: nil),
                     ], correctIndex: 1),
                     hint: "Area is linear in base.",
                     solutionSteps: ["½ · 2b · h = 2 · (½bh) = double"]),
            Question(id: "geo.tri.q4",
                     prompt: "Right triangle with legs 5 and 12. Area?",
                     math: nil, kind: .freeAnswer(accepted: ["30"]),
                     hint: "Legs are base and height.",
                     solutionSteps: ["A = ½ · 5 · 12 = 30"]),
            Question(id: "geo.tri.q5",
                     prompt: "True or false: any two triangles with the same base and height have the same area.",
                     math: nil, kind: .trueFalse(answer: true),
                     hint: "Look at the formula.",
                     solutionSteps: ["A = ½bh — same b, same h → same A."]),
        ]
    )

    // MARK: - Trigonometry

    static let trigBasics = Lesson(
        id: "trig.basics",
        title: "Trig Ratios",
        intro: "In a right triangle: SOH-CAH-TOA.",
        formulas: [
            Formula(key: "trig.basics.f1",
                    name: "Sine",
                    math: "sin θ = opposite / hypotenuse",
                    explanation: "Opposite over hypotenuse."),
            Formula(key: "trig.basics.f2",
                    name: "Cosine",
                    math: "cos θ = adjacent / hypotenuse",
                    explanation: "Adjacent over hypotenuse."),
            Formula(key: "trig.basics.f3",
                    name: "Tangent",
                    math: "tan θ = opposite / adjacent",
                    explanation: "Or sin θ / cos θ."),
        ],
        questions: [
            Question(id: "trig.basics.q1",
                     prompt: "What is sin 30°?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "1/2", math: nil),
                        .init(label: "√3/2", math: nil),
                        .init(label: "√2/2", math: nil),
                        .init(label: "1", math: nil),
                     ], correctIndex: 0),
                     hint: "Memorize the special angles.",
                     solutionSteps: ["sin 30° = 1/2"]),
            Question(id: "trig.basics.q2",
                     prompt: "True or false: sin²θ + cos²θ = 1 for every angle θ.",
                     math: nil, kind: .trueFalse(answer: true),
                     hint: "This is the Pythagorean identity.",
                     solutionSteps: ["By the Pythagorean identity."]),
            Question(id: "trig.basics.q3",
                     prompt: "What is cos 0°?",
                     math: nil, kind: .freeAnswer(accepted: ["1"]),
                     hint: "Adjacent equals hypotenuse at 0°.",
                     solutionSteps: ["cos 0° = 1"]),
            Question(id: "trig.basics.q4",
                     prompt: "What is tan 45°?",
                     math: nil, kind: .freeAnswer(accepted: ["1"]),
                     hint: "sin 45° = cos 45°.",
                     solutionSteps: ["tan 45° = 1"]),
            Question(id: "trig.basics.q5",
                     prompt: "Right triangle: opposite 3, hypotenuse 5. sin θ?",
                     math: nil, kind: .freeAnswer(accepted: ["3/5", "0.6"]),
                     hint: "SOH.",
                     solutionSteps: ["sin θ = 3/5"]),
        ]
    )

    static let unitCircle = Lesson(
        id: "trig.unit",
        title: "Unit Circle",
        intro: "On a circle of radius 1, sin and cos are coordinates.",
        formulas: [
            Formula(key: "trig.unit.f1",
                    name: "Coordinates",
                    math: "(cos θ, sin θ)  on  {var:x}{sup:^2} + {var:y}{sup:^2} = 1",
                    explanation: "Every angle picks a unique point."),
            Formula(key: "trig.unit.f2",
                    name: "Special values",
                    math: "0°→(1,0)  90°→(0,1)  180°→(−1,0)  270°→(0,−1)",
                    explanation: "Quadrant boundaries."),
        ],
        questions: [
            Question(id: "trig.unit.q1",
                     prompt: "What is cos 90°?",
                     math: nil, kind: .freeAnswer(accepted: ["0"]),
                     hint: "x-coordinate at the top of the circle.",
                     solutionSteps: ["cos 90° = 0"]),
            Question(id: "trig.unit.q2",
                     prompt: "What is sin 180°?",
                     math: nil, kind: .freeAnswer(accepted: ["0"]),
                     hint: "y-coordinate at the leftmost point.",
                     solutionSteps: ["sin 180° = 0"]),
            Question(id: "trig.unit.q3",
                     prompt: "Which angle has sine equal to 1?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "0°", math: nil),
                        .init(label: "90°", math: nil),
                        .init(label: "180°", math: nil),
                        .init(label: "360°", math: nil),
                     ], correctIndex: 1),
                     hint: "Top of the circle.",
                     solutionSteps: ["sin 90° = 1"]),
            Question(id: "trig.unit.q4",
                     prompt: "True or false: cos(360°) = cos(0°).",
                     math: nil, kind: .trueFalse(answer: true),
                     hint: "cos has period 360°.",
                     solutionSteps: ["A full revolution returns to the start."]),
            Question(id: "trig.unit.q5",
                     prompt: "What is tan 90°?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "1", math: nil),
                        .init(label: "0", math: nil),
                        .init(label: "Undefined", math: nil),
                        .init(label: "−1", math: nil),
                     ], correctIndex: 2),
                     hint: "tan = sin/cos and cos 90° = 0.",
                     solutionSteps: ["tan 90° is undefined (division by zero)."]),
        ]
    )

    // MARK: - Pre-Algebra (extended)

    static let preAlgNegatives = Lesson(
        id: "pre.neg",
        title: "Negative Numbers",
        intro: "Operations on numbers below zero. Two negatives multiplied give a positive.",
        formulas: [
            Formula(key: "pre.neg.f1",
                    name: "Sign rules",
                    math: "(−)·(−) = (+)    (−)·(+) = (−)",
                    explanation: "Same sign → positive product. Different sign → negative."),
            Formula(key: "pre.neg.f2",
                    name: "Subtracting a negative",
                    math: "{var:a} − (−{var:b}) = {var:a} + {var:b}",
                    explanation: "Two minuses cancel."),
        ],
        questions: [
            Question(id: "pre.neg.q1",
                     prompt: "Compute −7 + 3.", math: nil,
                     kind: .freeAnswer(accepted: ["-4", "−4"]),
                     hint: "Think of a number line.",
                     solutionSteps: ["−7 + 3 = −4"]),
            Question(id: "pre.neg.q2",
                     prompt: "Compute (−4)·(−5).", math: nil,
                     kind: .freeAnswer(accepted: ["20"]),
                     hint: "Two negatives → positive.",
                     solutionSteps: ["(−)(−) = (+)", "4 · 5 = 20"]),
            Question(id: "pre.neg.q3",
                     prompt: "Compute 3 − (−2).", math: nil,
                     kind: .freeAnswer(accepted: ["5"]),
                     hint: "Subtracting a negative is adding.",
                     solutionSteps: ["3 − (−2) = 3 + 2 = 5"]),
            Question(id: "pre.neg.q4",
                     prompt: "Which is largest?", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "−10", math: nil),
                        .init(label: "−5",  math: nil),
                        .init(label: "−1",  math: nil),
                        .init(label: "−100", math: nil),
                     ], correctIndex: 2),
                     hint: "Closer to zero = larger when negative.",
                     solutionSteps: ["−1 > −5 > −10 > −100"]),
            Question(id: "pre.neg.q5",
                     prompt: "True or false: |−7| = 7.", math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Absolute value strips the sign.",
                     solutionSteps: ["Distance from zero is 7."]),
        ]
    )

    // MARK: - Algebra (extended)

    static let factoring = Lesson(
        id: "alg.factor",
        title: "Factoring",
        intro: "Find the building blocks: factor common terms or recognize standard forms.",
        formulas: [
            Formula(key: "alg.factor.f1",
                    name: "Common factor",
                    math: "{var:a}{var:x} + {var:a}{var:y} = {var:a}({var:x} + {var:y})",
                    explanation: "Pull out what's shared."),
            Formula(key: "alg.factor.f2",
                    name: "Difference of squares",
                    math: "{var:a}{sup:^2} − {var:b}{sup:^2} = ({var:a} + {var:b})({var:a} − {var:b})",
                    explanation: "Two perfect squares minus → product of sum and difference."),
            Formula(key: "alg.factor.f3",
                    name: "Perfect square",
                    math: "{var:a}{sup:^2} + 2{var:a}{var:b} + {var:b}{sup:^2} = ({var:a} + {var:b}){sup:^2}",
                    explanation: "Recognize the pattern → square it back."),
        ],
        questions: [
            Question(id: "alg.factor.q1",
                     prompt: "Factor: x² − 9.", math: nil,
                     kind: .freeAnswer(accepted: ["(x-3)(x+3)", "(x+3)(x-3)"]),
                     hint: "Difference of squares.",
                     solutionSteps: ["x² − 3² = (x−3)(x+3)"]),
            Question(id: "alg.factor.q2",
                     prompt: "Factor: 6x + 9.", math: nil,
                     kind: .freeAnswer(accepted: ["3(2x+3)"]),
                     hint: "GCD of 6 and 9.",
                     solutionSteps: ["GCD = 3", "3(2x + 3)"]),
            Question(id: "alg.factor.q3",
                     prompt: "Factor: x² + 6x + 9.", math: nil,
                     kind: .freeAnswer(accepted: ["(x+3)^2", "(x+3)²", "(x+3)(x+3)"]),
                     hint: "Perfect square.",
                     solutionSteps: ["x² + 6x + 9 = (x + 3)²"]),
            Question(id: "alg.factor.q4",
                     prompt: "Which is a factor of x² + 5x + 6?", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "x + 1", math: nil),
                        .init(label: "x + 2", math: nil),
                        .init(label: "x − 3", math: nil),
                        .init(label: "x − 6", math: nil),
                     ], correctIndex: 1),
                     hint: "Find roots: numbers that multiply to 6, add to 5.",
                     solutionSteps: ["x² + 5x + 6 = (x + 2)(x + 3)"]),
            Question(id: "alg.factor.q5",
                     prompt: "True or false: 4x² − 25 = (2x − 5)(2x + 5).",
                     math: nil, kind: .trueFalse(answer: true),
                     hint: "Difference of squares with (2x)² and 5².",
                     solutionSteps: ["(2x)² − 5² = (2x−5)(2x+5)"]),
        ]
    )

    static let linesAndSlope = Lesson(
        id: "alg.line",
        title: "Slope & Lines",
        intro: "Lines have a slope and an intercept. Two points define them uniquely.",
        formulas: [
            Formula(key: "alg.line.f1",
                    name: "Slope from two points",
                    math: "{var:m} = ({var:y}{sub:_2} − {var:y}{sub:_1}) / ({var:x}{sub:_2} − {var:x}{sub:_1})",
                    explanation: "Rise over run."),
            Formula(key: "alg.line.f2",
                    name: "Slope-intercept form",
                    math: "{var:y} = {var:m}{var:x} + {var:b}",
                    explanation: "m is the slope, b is the y-intercept."),
        ],
        questions: [
            Question(id: "alg.line.q1",
                     prompt: "Slope through (1, 2) and (3, 8).", math: nil,
                     kind: .freeAnswer(accepted: ["3"]),
                     hint: "(8 − 2) / (3 − 1).",
                     solutionSteps: ["m = 6/2 = 3"]),
            Question(id: "alg.line.q2",
                     prompt: "Y-intercept of y = 2x − 5?", math: nil,
                     kind: .freeAnswer(accepted: ["-5", "−5"]),
                     hint: "Plug x = 0.",
                     solutionSteps: ["At x = 0: y = −5"]),
            Question(id: "alg.line.q3",
                     prompt: "Slope of a horizontal line is:", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "0", math: nil),
                        .init(label: "1", math: nil),
                        .init(label: "Undefined", math: nil),
                        .init(label: "Infinity", math: nil),
                     ], correctIndex: 0),
                     hint: "No vertical change.",
                     solutionSteps: ["Δy = 0", "m = 0"]),
            Question(id: "alg.line.q4",
                     prompt: "Through (0, 1) with slope 4. What's the y-value at x = 2?",
                     math: nil,
                     kind: .freeAnswer(accepted: ["9"]),
                     hint: "y = mx + b.",
                     solutionSteps: ["y = 4·2 + 1 = 9"]),
            Question(id: "alg.line.q5",
                     prompt: "True or false: y = 3 is a horizontal line.",
                     math: nil, kind: .trueFalse(answer: true),
                     hint: "Slope is zero.",
                     solutionSteps: ["For any x, y = 3 → horizontal."]),
        ]
    )

    // MARK: - Calculus (extended)

    static let chainRule = Lesson(
        id: "calc.chain",
        title: "Chain Rule",
        intro: "Differentiating compositions: outer derivative times inner derivative.",
        formulas: [
            Formula(key: "calc.chain.f1",
                    name: "Chain rule",
                    math: "({var:f} ∘ {var:g}){sup:^′}({var:x}) = {var:f}{sup:^′}({var:g}({var:x})) · {var:g}{sup:^′}({var:x})",
                    explanation: "Differentiate the outer function at the inner, then multiply by inner's derivative."),
        ],
        questions: [
            Question(id: "calc.chain.q1",
                     prompt: "Differentiate (3x + 2)⁴.", math: nil,
                     kind: .freeAnswer(accepted: ["12(3x+2)^3", "12(3x+2)³"]),
                     hint: "Outer 4·u³, inner derivative is 3.",
                     solutionSteps: ["4(3x+2)³ · 3 = 12(3x+2)³"]),
            Question(id: "calc.chain.q2",
                     prompt: "Differentiate sin(2x).", math: nil,
                     kind: .freeAnswer(accepted: ["2cos(2x)", "2 cos 2x", "2cos2x"]),
                     hint: "Outer is cos, inner derivative is 2.",
                     solutionSteps: ["cos(2x) · 2 = 2cos(2x)"]),
            Question(id: "calc.chain.q3",
                     prompt: "Differentiate (x² + 1)³.", math: nil,
                     kind: .freeAnswer(accepted: ["6x(x^2+1)^2", "6x(x²+1)²"]),
                     hint: "Outer 3·u², inner is 2x.",
                     solutionSteps: ["3(x²+1)² · 2x = 6x(x²+1)²"]),
            Question(id: "calc.chain.q4",
                     prompt: "True or false: d/dx √x = 1/(2√x).",
                     math: nil, kind: .trueFalse(answer: true),
                     hint: "Power rule with 1/2.",
                     solutionSteps: ["√x = x^(1/2)", "Derivative: (1/2)x^(−1/2) = 1/(2√x)"]),
            Question(id: "calc.chain.q5",
                     prompt: "Differentiate e^(3x).", math: nil,
                     kind: .freeAnswer(accepted: ["3e^(3x)", "3e^3x"]),
                     hint: "e^u stays, inner derivative is 3.",
                     solutionSteps: ["e^(3x) · 3 = 3e^(3x)"]),
        ]
    )

    // MARK: - Geometry (extended)

    static let volumes = Lesson(
        id: "geo.vol",
        title: "Volumes",
        intro: "Three-dimensional measure of common solids.",
        formulas: [
            Formula(key: "geo.vol.f1",
                    name: "Cube",
                    math: "{var:V} = {var:s}{sup:^3}",
                    explanation: "Side cubed."),
            Formula(key: "geo.vol.f2",
                    name: "Cylinder",
                    math: "{var:V} = π{var:r}{sup:^2}{var:h}",
                    explanation: "Base area times height."),
            Formula(key: "geo.vol.f3",
                    name: "Sphere",
                    math: "{var:V} = (4/3)π{var:r}{sup:^3}",
                    explanation: "Memorize the 4/3."),
        ],
        questions: [
            Question(id: "geo.vol.q1",
                     prompt: "Volume of a cube with side 4?",
                     math: nil, kind: .freeAnswer(accepted: ["64"]),
                     hint: "s³.",
                     solutionSteps: ["4³ = 64"]),
            Question(id: "geo.vol.q2",
                     prompt: "Volume of a cylinder with radius 2 and height 5? In terms of π.",
                     math: nil, kind: .freeAnswer(accepted: ["20pi", "20π"]),
                     hint: "πr²h.",
                     solutionSteps: ["π · 4 · 5 = 20π"]),
            Question(id: "geo.vol.q3",
                     prompt: "Volume of a sphere with radius 3? In terms of π.",
                     math: nil, kind: .freeAnswer(accepted: ["36pi", "36π"]),
                     hint: "(4/3)πr³.",
                     solutionSteps: ["(4/3)π·27 = 36π"]),
            Question(id: "geo.vol.q4",
                     prompt: "Doubling the radius of a sphere multiplies the volume by:",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "2", math: nil),
                        .init(label: "4", math: nil),
                        .init(label: "6", math: nil),
                        .init(label: "8", math: nil),
                     ], correctIndex: 3),
                     hint: "Volume scales with r³.",
                     solutionSteps: ["(2r)³ = 8r³"]),
            Question(id: "geo.vol.q5",
                     prompt: "True or false: a 1×1×1 cube has volume 1.",
                     math: nil, kind: .trueFalse(answer: true),
                     hint: "1³.",
                     solutionSteps: ["1·1·1 = 1"]),
        ]
    )

    // MARK: - Trig (extended)

    static let trigIdentities = Lesson(
        id: "trig.id",
        title: "Trig Identities",
        intro: "Identities that always hold. The Pythagorean one is the keystone.",
        formulas: [
            Formula(key: "trig.id.f1",
                    name: "Pythagorean",
                    math: "sin{sup:^2}θ + cos{sup:^2}θ = 1",
                    explanation: "Direct from the unit circle."),
            Formula(key: "trig.id.f2",
                    name: "Tangent identity",
                    math: "tan θ = sin θ / cos θ",
                    explanation: "Whenever cos θ ≠ 0."),
            Formula(key: "trig.id.f3",
                    name: "Even / odd",
                    math: "cos(−θ) = cos θ    sin(−θ) = −sin θ",
                    explanation: "cos is even; sin is odd."),
        ],
        questions: [
            Question(id: "trig.id.q1",
                     prompt: "If sin θ = 3/5 and θ is in Q1, what is cos θ?",
                     math: nil, kind: .freeAnswer(accepted: ["4/5", "0.8"]),
                     hint: "Use sin² + cos² = 1.",
                     solutionSteps: ["cos² = 1 − 9/25 = 16/25", "cos = 4/5 (Q1)"]),
            Question(id: "trig.id.q2",
                     prompt: "Simplify sin(−x) + sin(x).",
                     math: nil, kind: .freeAnswer(accepted: ["0"]),
                     hint: "sin is odd.",
                     solutionSteps: ["sin(−x) = −sin(x)", "−sin(x) + sin(x) = 0"]),
            Question(id: "trig.id.q3",
                     prompt: "True or false: cos(−π) = cos(π).",
                     math: nil, kind: .trueFalse(answer: true),
                     hint: "cos is even.",
                     solutionSteps: ["cos(−x) = cos(x) for all x."]),
            Question(id: "trig.id.q4",
                     prompt: "What does tan θ · cos θ simplify to?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "sin θ", math: nil),
                        .init(label: "cos θ", math: nil),
                        .init(label: "1", math: nil),
                        .init(label: "θ", math: nil),
                     ], correctIndex: 0),
                     hint: "Substitute the tangent identity.",
                     solutionSteps: ["(sin θ / cos θ) · cos θ = sin θ"]),
            Question(id: "trig.id.q5",
                     prompt: "If cos θ = 0, sin θ equals?", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "0",   math: nil),
                        .init(label: "±1",  math: nil),
                        .init(label: "1/2", math: nil),
                        .init(label: "Undefined", math: nil),
                     ], correctIndex: 1),
                     hint: "sin² + cos² = 1.",
                     solutionSteps: ["sin² = 1 → sin = ±1"]),
        ]
    )

    // MARK: - Pre-Algebra (more)

    static let preAlgDecimals = Lesson(
        id: "pre.dec",
        title: "Decimals",
        intro: "Decimals are just fractions written with place value. Line up the points and the rest follows.",
        formulas: [
            Formula(key: "pre.dec.f1",
                    name: "Fraction to decimal",
                    math: "{var:a}/{var:b} = {var:a} ÷ {var:b}",
                    explanation: "Divide the top by the bottom."),
            Formula(key: "pre.dec.f2",
                    name: "Multiplying decimals",
                    math: "count decimal places, then place the point",
                    explanation: "The product has as many decimal places as both factors combined."),
        ],
        questions: [
            Question(id: "pre.dec.q1",
                     prompt: "Compute 0.25 + 0.4.", math: nil,
                     kind: .freeAnswer(accepted: ["0.65"]),
                     hint: "Line up the decimal points: 0.25 + 0.40.",
                     solutionSteps: ["0.25 + 0.40 = 0.65"]),
            Question(id: "pre.dec.q2",
                     prompt: "Compute 1.2 × 0.3.", math: nil,
                     kind: .freeAnswer(accepted: ["0.36"]),
                     hint: "Multiply 12 × 3, then place two decimal places.",
                     solutionSteps: ["12 × 3 = 36", "Two decimal places total → 0.36"]),
            Question(id: "pre.dec.q3",
                     prompt: "Write 3/4 as a decimal.", math: nil,
                     kind: .freeAnswer(accepted: ["0.75", ".75"]),
                     hint: "Divide 3 by 4.",
                     solutionSteps: ["3 ÷ 4 = 0.75"]),
            Question(id: "pre.dec.q4",
                     prompt: "Which is largest?", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "0.7", math: nil),
                        .init(label: "0.07", math: nil),
                        .init(label: "0.707", math: nil),
                        .init(label: "0.077", math: nil),
                     ], correctIndex: 2),
                     hint: "Compare place by place after the point.",
                     solutionSteps: ["0.707 > 0.7 > 0.077 > 0.07"]),
            Question(id: "pre.dec.q5",
                     prompt: "True or false: 0.5 equals 1/2.", math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Five tenths.",
                     solutionSteps: ["0.5 = 5/10 = 1/2"]),
        ]
    )

    static let preAlgRatios = Lesson(
        id: "pre.ratio",
        title: "Ratios & Proportions",
        intro: "A ratio compares two quantities. A proportion says two ratios are equal.",
        formulas: [
            Formula(key: "pre.ratio.f1",
                    name: "Ratio as a fraction",
                    math: "{var:a} : {var:b} = {var:a}/{var:b}",
                    explanation: "Simplify it like any fraction."),
            Formula(key: "pre.ratio.f2",
                    name: "Cross-multiply",
                    math: "{var:a}/{var:b} = {var:c}/{var:d}  ⟹  {var:a}{var:d} = {var:b}{var:c}",
                    explanation: "Solve a proportion by cross-multiplying."),
        ],
        questions: [
            Question(id: "pre.ratio.q1",
                     prompt: "Simplify the ratio 12 : 18.", math: nil,
                     kind: .freeAnswer(accepted: ["2:3"]),
                     hint: "Divide both sides by their common factor, 6.",
                     solutionSteps: ["GCD(12, 18) = 6", "12 : 18 = 2 : 3"]),
            Question(id: "pre.ratio.q2",
                     prompt: "If 3 pens cost $6, what do 5 pens cost?", math: nil,
                     kind: .freeAnswer(accepted: ["10", "$10"]),
                     hint: "One pen costs $2.",
                     solutionSteps: ["6 ÷ 3 = $2 per pen", "5 × 2 = $10"]),
            Question(id: "pre.ratio.q3",
                     prompt: "Solve the proportion x / 4 = 9 / 12.", math: nil,
                     kind: .freeAnswer(accepted: ["3"]),
                     hint: "Cross-multiply: 12x = 36.",
                     solutionSteps: ["12x = 4 · 9 = 36", "x = 3"]),
            Question(id: "pre.ratio.q4",
                     prompt: "Which ratio is equivalent to 2 : 5?", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "4 : 10", math: nil),
                        .init(label: "5 : 2", math: nil),
                        .init(label: "3 : 6", math: nil),
                        .init(label: "2 : 7", math: nil),
                     ], correctIndex: 0),
                     hint: "Multiply both parts by the same number.",
                     solutionSteps: ["2 : 5 = (2·2) : (5·2) = 4 : 10"]),
            Question(id: "pre.ratio.q5",
                     prompt: "True or false: the ratio 1 : 2 is the same as 2 : 4.", math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Simplify 2 : 4.",
                     solutionSteps: ["2 : 4 = 1 : 2"]),
        ]
    )

    static let preAlgRoots = Lesson(
        id: "pre.roots",
        title: "Powers & Roots",
        intro: "A power multiplies a number by itself; a root undoes a power.",
        formulas: [
            Formula(key: "pre.roots.f1",
                    name: "Square and square root",
                    math: "{var:n}{sup:^2} = {var:n}·{var:n}    √({var:n}{sup:^2}) = {var:n}",
                    explanation: "Squaring and taking the square root are inverses."),
            Formula(key: "pre.roots.f2",
                    name: "Perfect squares",
                    math: "1, 4, 9, 16, 25, 36, 49, 64, 81, 100",
                    explanation: "Memorizing these makes roots fast."),
        ],
        questions: [
            Question(id: "pre.roots.q1",
                     prompt: "Compute 7².", math: nil,
                     kind: .freeAnswer(accepted: ["49"]),
                     hint: "7 × 7.",
                     solutionSteps: ["7 · 7 = 49"]),
            Question(id: "pre.roots.q2",
                     prompt: "Compute √81.", math: nil,
                     kind: .freeAnswer(accepted: ["9"]),
                     hint: "What number squared gives 81?",
                     solutionSteps: ["9² = 81, so √81 = 9"]),
            Question(id: "pre.roots.q3",
                     prompt: "Compute 2⁵.", math: nil,
                     kind: .freeAnswer(accepted: ["32"]),
                     hint: "Multiply 2 by itself five times.",
                     solutionSteps: ["2·2·2·2·2 = 32"]),
            Question(id: "pre.roots.q4",
                     prompt: "√50 lies between which two whole numbers?", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "6 and 7", math: nil),
                        .init(label: "7 and 8", math: nil),
                        .init(label: "8 and 9", math: nil),
                        .init(label: "5 and 6", math: nil),
                     ], correctIndex: 1),
                     hint: "7² = 49 and 8² = 64.",
                     solutionSteps: ["49 < 50 < 64", "So 7 < √50 < 8"]),
            Question(id: "pre.roots.q5",
                     prompt: "True or false: the cube root of 27 is 3.", math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "3 × 3 × 3.",
                     solutionSteps: ["3³ = 27, so ∛27 = 3"]),
        ]
    )

    // MARK: - Algebra (more)

    static let inequalities = Lesson(
        id: "alg.ineq",
        title: "Inequalities",
        intro: "Solve inequalities like equations — with one twist: flip the sign when you multiply or divide by a negative.",
        formulas: [
            Formula(key: "alg.ineq.f1",
                    name: "Same as equations",
                    math: "{var:x} + {var:a} < {var:b}  ⟹  {var:x} < {var:b} − {var:a}",
                    explanation: "Add and subtract on both sides freely."),
            Formula(key: "alg.ineq.f2",
                    name: "Flip on a negative",
                    math: "−{var:a}{var:x} < {var:b}  ⟹  {var:x} > −{var:b}/{var:a}",
                    explanation: "Dividing by a negative reverses the inequality."),
        ],
        questions: [
            Question(id: "alg.ineq.q1",
                     prompt: "Solve x + 3 < 7.", math: nil,
                     kind: .freeAnswer(accepted: ["x<4"]),
                     hint: "Subtract 3 from both sides.",
                     solutionSteps: ["x < 7 − 3", "x < 4"]),
            Question(id: "alg.ineq.q2",
                     prompt: "Solve 2x ≥ 10.", math: nil,
                     kind: .freeAnswer(accepted: ["x>=5"]),
                     hint: "Divide both sides by 2.",
                     solutionSteps: ["x ≥ 10 / 2", "x ≥ 5"]),
            Question(id: "alg.ineq.q3",
                     prompt: "Solve −3x < 9.", math: nil,
                     kind: .freeAnswer(accepted: ["x>-3"]),
                     hint: "Divide by −3 — and flip the sign.",
                     solutionSteps: ["Divide by −3 and reverse: x > 9 / (−3)", "x > −3"]),
            Question(id: "alg.ineq.q4",
                     prompt: "When you divide both sides of an inequality by a negative number, the sign:",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "Stays the same", math: nil),
                        .init(label: "Reverses", math: nil),
                        .init(label: "Becomes an equals sign", math: nil),
                        .init(label: "Disappears", math: nil),
                     ], correctIndex: 1),
                     hint: "Test it with −2 < 4.",
                     solutionSteps: ["−2 < 4 is true", "Divide by −2: 1 > −2 — the sign reversed"]),
            Question(id: "alg.ineq.q5",
                     prompt: "True or false: the solution x > 5 includes the value x = 5.",
                     math: nil,
                     kind: .trueFalse(answer: false),
                     hint: "Strictly greater than.",
                     solutionSteps: ["x > 5 means strictly above 5", "x = 5 is not included"]),
        ]
    )

    static let systems = Lesson(
        id: "alg.sys",
        title: "Systems of Equations",
        intro: "Two equations, two unknowns. Solve by substitution or by elimination.",
        formulas: [
            Formula(key: "alg.sys.f1",
                    name: "Elimination",
                    math: "add or subtract the equations to cancel one variable",
                    explanation: "Line them up so one variable drops out."),
            Formula(key: "alg.sys.f2",
                    name: "Substitution",
                    math: "solve one equation for a variable, plug into the other",
                    explanation: "Reduces the system to a single equation."),
        ],
        questions: [
            Question(id: "alg.sys.q1",
                     prompt: "Given x + y = 10 and x − y = 4, find x.", math: nil,
                     kind: .freeAnswer(accepted: ["7"]),
                     hint: "Add the two equations — the y terms cancel.",
                     solutionSteps: ["Add: 2x = 14", "x = 7"]),
            Question(id: "alg.sys.q2",
                     prompt: "Given x + y = 10 and x − y = 4, find y.", math: nil,
                     kind: .freeAnswer(accepted: ["3"]),
                     hint: "You already know x = 7.",
                     solutionSteps: ["7 + y = 10", "y = 3"]),
            Question(id: "alg.sys.q3",
                     prompt: "How many solutions does the system y = x, y = x + 1 have?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "None", math: nil),
                        .init(label: "Exactly one", math: nil),
                        .init(label: "Exactly two", math: nil),
                        .init(label: "Infinitely many", math: nil),
                     ], correctIndex: 0),
                     hint: "The lines have the same slope.",
                     solutionSteps: ["Parallel lines never meet", "No solution"]),
            Question(id: "alg.sys.q4",
                     prompt: "If 2x + y = 7 and y = 3, then x =", math: nil,
                     kind: .freeAnswer(accepted: ["2"]),
                     hint: "Substitute y = 3.",
                     solutionSteps: ["2x + 3 = 7", "2x = 4", "x = 2"]),
            Question(id: "alg.sys.q5",
                     prompt: "True or false: two parallel lines form a system with no solution.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Where do parallel lines cross?",
                     solutionSteps: ["Parallel lines never intersect → no shared point"]),
        ]
    )

    static let polynomials = Lesson(
        id: "alg.poly",
        title: "Polynomials",
        intro: "Polynomials are sums of terms. Combine like terms, and multiply binomials with FOIL.",
        formulas: [
            Formula(key: "alg.poly.f1",
                    name: "Combine like terms",
                    math: "{var:a}{var:x} + {var:b}{var:x} = ({var:a} + {var:b}){var:x}",
                    explanation: "Only terms with the same variable and power combine."),
            Formula(key: "alg.poly.f2",
                    name: "FOIL",
                    math: "({var:x} + {var:a})({var:x} + {var:b}) = {var:x}{sup:^2} + ({var:a}+{var:b}){var:x} + {var:a}{var:b}",
                    explanation: "First, Outer, Inner, Last."),
        ],
        questions: [
            Question(id: "alg.poly.q1",
                     prompt: "Simplify 3x + 5x − 2x.", math: nil,
                     kind: .freeAnswer(accepted: ["6x"]),
                     hint: "All terms are like terms.",
                     solutionSteps: ["3 + 5 − 2 = 6", "Result: 6x"]),
            Question(id: "alg.poly.q2",
                     prompt: "Expand (x + 2)(x + 3).", math: nil,
                     kind: .freeAnswer(accepted: ["x^2+5x+6"]),
                     hint: "Use FOIL.",
                     solutionSteps: ["First: x²", "Outer + Inner: 3x + 2x = 5x", "Last: 6", "x² + 5x + 6"]),
            Question(id: "alg.poly.q3",
                     prompt: "Add (2x² + 3x) + (x² − x).", math: nil,
                     kind: .freeAnswer(accepted: ["3x^2+2x"]),
                     hint: "Combine the x² terms, then the x terms.",
                     solutionSteps: ["2x² + x² = 3x²", "3x − x = 2x", "3x² + 2x"]),
            Question(id: "alg.poly.q4",
                     prompt: "What is the degree of 4x³ − x + 7?", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "1", math: nil),
                        .init(label: "3", math: nil),
                        .init(label: "4", math: nil),
                        .init(label: "7", math: nil),
                     ], correctIndex: 1),
                     hint: "The degree is the highest exponent.",
                     solutionSteps: ["Highest power is x³ → degree 3"]),
            Question(id: "alg.poly.q5",
                     prompt: "True or false: x² + 2x + 1 = (x + 1)².", math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Expand (x + 1)².",
                     solutionSteps: ["(x + 1)² = x² + 2x + 1"]),
        ]
    )

    static let algFunctions = Lesson(
        id: "alg.func",
        title: "Functions",
        intro: "A function takes an input and returns exactly one output. f(x) is read 'f of x'.",
        formulas: [
            Formula(key: "alg.func.f1",
                    name: "Function notation",
                    math: "{var:f}({var:x}) = output for input {var:x}",
                    explanation: "Substitute the input wherever x appears."),
            Formula(key: "alg.func.f2",
                    name: "Domain",
                    math: "domain = all valid inputs",
                    explanation: "Exclude inputs that break the rule, like dividing by zero."),
        ],
        questions: [
            Question(id: "alg.func.q1",
                     prompt: "If f(x) = 2x + 1, find f(3).", math: nil,
                     kind: .freeAnswer(accepted: ["7"]),
                     hint: "Replace x with 3.",
                     solutionSteps: ["f(3) = 2·3 + 1", "= 7"]),
            Question(id: "alg.func.q2",
                     prompt: "If f(x) = x² − 4, find f(2).", math: nil,
                     kind: .freeAnswer(accepted: ["0"]),
                     hint: "Square the input first.",
                     solutionSteps: ["f(2) = 2² − 4", "= 4 − 4 = 0"]),
            Question(id: "alg.func.q3",
                     prompt: "The domain of f(x) = 1/x excludes which value?", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "x = 1", math: nil),
                        .init(label: "x = 0", math: nil),
                        .init(label: "x = −1", math: nil),
                        .init(label: "No value is excluded", math: nil),
                     ], correctIndex: 1),
                     hint: "You can't divide by zero.",
                     solutionSteps: ["1/0 is undefined", "x = 0 is excluded"]),
            Question(id: "alg.func.q4",
                     prompt: "If g(x) = 5 for every x, what is g(100)?", math: nil,
                     kind: .freeAnswer(accepted: ["5"]),
                     hint: "It's a constant function.",
                     solutionSteps: ["g returns 5 no matter the input", "g(100) = 5"]),
            Question(id: "alg.func.q5",
                     prompt: "True or false: f(x) = x² gives the same output for x = 2 and x = −2.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Square both.",
                     solutionSteps: ["2² = 4 and (−2)² = 4", "Same output"]),
        ]
    )

    // MARK: - Calculus (more)

    static let productQuotient = Lesson(
        id: "calc.pq",
        title: "Product & Quotient Rule",
        intro: "Derivatives of products and quotients aren't just the product of derivatives — they have their own rules.",
        formulas: [
            Formula(key: "calc.pq.f1",
                    name: "Product rule",
                    math: "({var:f}·{var:g}){sup:^′} = {var:f}{sup:^′}{var:g} + {var:f}{var:g}{sup:^′}",
                    explanation: "Derivative of the first times the second, plus the first times the derivative of the second."),
            Formula(key: "calc.pq.f2",
                    name: "Quotient rule",
                    math: "({var:f}/{var:g}){sup:^′} = ({var:f}{sup:^′}{var:g} − {var:f}{var:g}{sup:^′}) / {var:g}{sup:^2}",
                    explanation: "Low d-high minus high d-low, over the square of the bottom."),
        ],
        questions: [
            Question(id: "calc.pq.q1",
                     prompt: "The product rule says (f·g)′ equals:", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "f′g′", math: nil),
                        .init(label: "f′g + fg′", math: nil),
                        .init(label: "f′g − fg′", math: nil),
                        .init(label: "f′ + g′", math: nil),
                     ], correctIndex: 1),
                     hint: "It is not simply the product of the two derivatives.",
                     solutionSteps: ["(f·g)′ = f′g + fg′"]),
            Question(id: "calc.pq.q2",
                     prompt: "Differentiate (x + 1)(x + 4).", math: nil,
                     kind: .freeAnswer(accepted: ["2x+5"]),
                     hint: "Product rule: (1)(x+4) + (x+1)(1).",
                     solutionSteps: ["f′g = 1·(x+4) = x+4", "fg′ = (x+1)·1 = x+1", "Sum: 2x + 5"]),
            Question(id: "calc.pq.q3",
                     prompt: "True or false: d/dx (1/x) = −1/x².", math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Write 1/x as x⁻¹ and use the power rule.",
                     solutionSteps: ["x⁻¹ → −1·x⁻² = −1/x²"]),
            Question(id: "calc.pq.q4",
                     prompt: "In the quotient rule (f/g)′, the numerator is:", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "f′g + fg′", math: nil),
                        .init(label: "f′g − fg′", math: nil),
                        .init(label: "fg′ − f′g", math: nil),
                        .init(label: "f′g′", math: nil),
                     ], correctIndex: 1),
                     hint: "Low d-high minus high d-low.",
                     solutionSteps: ["Numerator = f′g − fg′"]),
            Question(id: "calc.pq.q5",
                     prompt: "Use the product rule on x · x. The derivative is:", math: nil,
                     kind: .freeAnswer(accepted: ["2x"]),
                     hint: "f′g + fg′ with f = g = x.",
                     solutionSteps: ["(1)(x) + (x)(1) = 2x"]),
        ]
    )

    static let definiteIntegrals = Lesson(
        id: "calc.defint",
        title: "Definite Integrals",
        intro: "A definite integral measures accumulated change — the signed area under a curve between two limits.",
        formulas: [
            Formula(key: "calc.defint.f1",
                    name: "Fundamental theorem",
                    math: "∫{sub:_a}{sup:^b} {var:f}({var:x}) d{var:x} = {var:F}({var:b}) − {var:F}({var:a})",
                    explanation: "Evaluate the antiderivative at both limits and subtract."),
            Formula(key: "calc.defint.f2",
                    name: "Zero-width interval",
                    math: "∫{sub:_a}{sup:^a} {var:f}({var:x}) d{var:x} = 0",
                    explanation: "No interval means no area."),
        ],
        questions: [
            Question(id: "calc.defint.q1",
                     prompt: "Evaluate ∫₀² 2x dx.", math: nil,
                     kind: .freeAnswer(accepted: ["4"]),
                     hint: "Antiderivative of 2x is x².",
                     solutionSteps: ["∫ 2x dx = x²", "x² from 0 to 2 = 4 − 0 = 4"]),
            Question(id: "calc.defint.q2",
                     prompt: "Evaluate ∫₁³ 1 dx.", math: nil,
                     kind: .freeAnswer(accepted: ["2"]),
                     hint: "Antiderivative of 1 is x.",
                     solutionSteps: ["∫ 1 dx = x", "x from 1 to 3 = 3 − 1 = 2"]),
            Question(id: "calc.defint.q3",
                     prompt: "What is ∫ₐᵃ f(x) dx?", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "0", math: nil),
                        .init(label: "1", math: nil),
                        .init(label: "f(a)", math: nil),
                        .init(label: "Undefined", math: nil),
                     ], correctIndex: 0),
                     hint: "The interval has zero width.",
                     solutionSteps: ["F(a) − F(a) = 0"]),
            Question(id: "calc.defint.q4",
                     prompt: "Evaluate ∫₀¹ 3x² dx.", math: nil,
                     kind: .freeAnswer(accepted: ["1"]),
                     hint: "Antiderivative of 3x² is x³.",
                     solutionSteps: ["∫ 3x² dx = x³", "x³ from 0 to 1 = 1 − 0 = 1"]),
            Question(id: "calc.defint.q5",
                     prompt: "True or false: a definite integral can represent the area under a curve.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Think of summing thin rectangles.",
                     solutionSteps: ["The definite integral is the limit of a sum of areas"]),
        ]
    )

    static let calcApplications = Lesson(
        id: "calc.apps",
        title: "Applications of Derivatives",
        intro: "Derivatives describe motion, growth, and shape — slope, velocity, maxima and minima.",
        formulas: [
            Formula(key: "calc.apps.f1",
                    name: "Critical points",
                    math: "{var:f}{sup:^′}({var:x}) = 0  at maxima and minima",
                    explanation: "A smooth peak or valley has a flat tangent."),
            Formula(key: "calc.apps.f2",
                    name: "Increasing / decreasing",
                    math: "{var:f}{sup:^′} > 0 → rising    {var:f}{sup:^′} < 0 → falling",
                    explanation: "The sign of the derivative is the direction of the curve."),
        ],
        questions: [
            Question(id: "calc.apps.q1",
                     prompt: "At a smooth maximum of a function, f′(x) equals:", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "0", math: nil),
                        .init(label: "1", math: nil),
                        .init(label: "Undefined", math: nil),
                        .init(label: "The maximum value", math: nil),
                     ], correctIndex: 0),
                     hint: "The tangent line is flat there.",
                     solutionSteps: ["A smooth peak has slope 0 → f′(x) = 0"]),
            Question(id: "calc.apps.q2",
                     prompt: "f(x) = x² − 4x. At what x is the minimum?", math: nil,
                     kind: .freeAnswer(accepted: ["2"]),
                     hint: "Set f′(x) = 2x − 4 equal to 0.",
                     solutionSteps: ["f′(x) = 2x − 4", "2x − 4 = 0", "x = 2"]),
            Question(id: "calc.apps.q3",
                     prompt: "True or false: if f′(x) > 0, then f is increasing there.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Positive slope.",
                     solutionSteps: ["A positive derivative means the function rises"]),
            Question(id: "calc.apps.q4",
                     prompt: "The second derivative f″(x) tells you about a curve's:", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "Concavity", math: nil),
                        .init(label: "y-intercept", math: nil),
                        .init(label: "Domain", math: nil),
                        .init(label: "Period", math: nil),
                     ], correctIndex: 0),
                     hint: "It's the rate of change of the slope.",
                     solutionSteps: ["f″ > 0 → concave up, f″ < 0 → concave down"]),
            Question(id: "calc.apps.q5",
                     prompt: "A ball's height is h(t) = −t² + 4t. Its velocity h′(t) at t = 1 is:",
                     math: nil,
                     kind: .freeAnswer(accepted: ["2"]),
                     hint: "h′(t) = −2t + 4.",
                     solutionSteps: ["h′(t) = −2t + 4", "h′(1) = −2 + 4 = 2"]),
        ]
    )

    // MARK: - Geometry (more)

    static let angles = Lesson(
        id: "geo.angle",
        title: "Angles",
        intro: "Angles on a line, in a triangle, and around a point all add to fixed totals.",
        formulas: [
            Formula(key: "geo.angle.f1",
                    name: "Straight line",
                    math: "angles on a line sum to 180°",
                    explanation: "A straight angle is 180°."),
            Formula(key: "geo.angle.f2",
                    name: "Triangle",
                    math: "interior angles of a triangle sum to 180°",
                    explanation: "True for every triangle."),
        ],
        questions: [
            Question(id: "geo.angle.q1",
                     prompt: "Two angles sit on a straight line. One is 110°. The other is:",
                     math: nil,
                     kind: .freeAnswer(accepted: ["70", "70°"]),
                     hint: "They must sum to 180°.",
                     solutionSteps: ["180° − 110° = 70°"]),
            Question(id: "geo.angle.q2",
                     prompt: "A triangle has angles of 50° and 60°. The third angle is:",
                     math: nil,
                     kind: .freeAnswer(accepted: ["70", "70°"]),
                     hint: "All three sum to 180°.",
                     solutionSteps: ["180° − 50° − 60° = 70°"]),
            Question(id: "geo.angle.q3",
                     prompt: "A right angle measures:", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "45°", math: nil),
                        .init(label: "90°", math: nil),
                        .init(label: "180°", math: nil),
                        .init(label: "360°", math: nil),
                     ], correctIndex: 1),
                     hint: "A square corner.",
                     solutionSteps: ["A right angle is 90°"]),
            Question(id: "geo.angle.q4",
                     prompt: "Complementary angles sum to:", math: nil,
                     kind: .freeAnswer(accepted: ["90", "90°"]),
                     hint: "Not supplementary — that's 180°.",
                     solutionSteps: ["Complementary angles add to 90°"]),
            Question(id: "geo.angle.q5",
                     prompt: "True or false: vertical angles are always equal.", math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Two lines crossing make two pairs.",
                     solutionSteps: ["Opposite (vertical) angles at an intersection are congruent"]),
        ]
    )

    static let quadrilaterals = Lesson(
        id: "geo.quad",
        title: "Quadrilaterals",
        intro: "Four-sided shapes: rectangles, squares, and parallelograms each have tidy area rules.",
        formulas: [
            Formula(key: "geo.quad.f1",
                    name: "Rectangle area",
                    math: "{var:A} = {var:l}·{var:w}",
                    explanation: "Length times width."),
            Formula(key: "geo.quad.f2",
                    name: "Parallelogram area",
                    math: "{var:A} = {var:b}·{var:h}",
                    explanation: "Base times perpendicular height."),
            Formula(key: "geo.quad.f3",
                    name: "Interior angles",
                    math: "angles of a quadrilateral sum to 360°",
                    explanation: "Two triangles' worth."),
        ],
        questions: [
            Question(id: "geo.quad.q1",
                     prompt: "Area of a rectangle 8 by 3?", math: nil,
                     kind: .freeAnswer(accepted: ["24"]),
                     hint: "Length times width.",
                     solutionSteps: ["8 · 3 = 24"]),
            Question(id: "geo.quad.q2",
                     prompt: "Perimeter of a square with side 5?", math: nil,
                     kind: .freeAnswer(accepted: ["20"]),
                     hint: "Four equal sides.",
                     solutionSteps: ["4 · 5 = 20"]),
            Question(id: "geo.quad.q3",
                     prompt: "The interior angles of any quadrilateral sum to:", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "180°", math: nil),
                        .init(label: "270°", math: nil),
                        .init(label: "360°", math: nil),
                        .init(label: "540°", math: nil),
                     ], correctIndex: 2),
                     hint: "It splits into two triangles.",
                     solutionSteps: ["2 triangles × 180° = 360°"]),
            Question(id: "geo.quad.q4",
                     prompt: "Area of a parallelogram with base 6 and height 4?", math: nil,
                     kind: .freeAnswer(accepted: ["24"]),
                     hint: "Base times height.",
                     solutionSteps: ["6 · 4 = 24"]),
            Question(id: "geo.quad.q5",
                     prompt: "True or false: every square is also a rectangle.", math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "A square meets the rectangle definition.",
                     solutionSteps: ["A square has four right angles → it is a rectangle"]),
        ]
    )

    static let geoSurfaceArea = Lesson(
        id: "geo.surf",
        title: "Surface Area",
        intro: "Surface area is the total area of every face of a solid — measured in square units.",
        formulas: [
            Formula(key: "geo.surf.f1",
                    name: "Cube",
                    math: "{var:S} = 6{var:s}{sup:^2}",
                    explanation: "Six identical square faces."),
            Formula(key: "geo.surf.f2",
                    name: "Sphere",
                    math: "{var:S} = 4π{var:r}{sup:^2}",
                    explanation: "Four times the area of a great circle."),
        ],
        questions: [
            Question(id: "geo.surf.q1",
                     prompt: "Surface area of a cube with side 2?", math: nil,
                     kind: .freeAnswer(accepted: ["24"]),
                     hint: "6s².",
                     solutionSteps: ["6 · 2² = 6 · 4 = 24"]),
            Question(id: "geo.surf.q2",
                     prompt: "Surface area of a sphere with radius 1? In terms of π.", math: nil,
                     kind: .freeAnswer(accepted: ["4pi", "4π"]),
                     hint: "4πr².",
                     solutionSteps: ["4π · 1² = 4π"]),
            Question(id: "geo.surf.q3",
                     prompt: "The surface area of a cube is:", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "s³", math: nil),
                        .init(label: "6s²", math: nil),
                        .init(label: "4s²", math: nil),
                        .init(label: "2s", math: nil),
                     ], correctIndex: 1),
                     hint: "Count the faces.",
                     solutionSteps: ["A cube has 6 faces, each s² → 6s²"]),
            Question(id: "geo.surf.q4",
                     prompt: "Surface area of a cube with side 5?", math: nil,
                     kind: .freeAnswer(accepted: ["150"]),
                     hint: "6 · 5².",
                     solutionSteps: ["6 · 25 = 150"]),
            Question(id: "geo.surf.q5",
                     prompt: "True or false: surface area is measured in square units.", math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "It's an area, not a volume.",
                     solutionSteps: ["Area → square units; volume → cubic units"]),
        ]
    )

    // MARK: - Trigonometry (more)

    static let radians = Lesson(
        id: "trig.rad",
        title: "Radians & Degrees",
        intro: "Radians measure angles by arc length. Half a circle is π radians.",
        formulas: [
            Formula(key: "trig.rad.f1",
                    name: "Half turn",
                    math: "180° = π rad",
                    explanation: "The bridge between the two units."),
            Formula(key: "trig.rad.f2",
                    name: "Conversion",
                    math: "rad = deg · π/180     deg = rad · 180/π",
                    explanation: "Multiply by the matching factor."),
        ],
        questions: [
            Question(id: "trig.rad.q1",
                     prompt: "Convert 180° to radians. In terms of π.", math: nil,
                     kind: .freeAnswer(accepted: ["pi", "π"]),
                     hint: "Half a circle.",
                     solutionSteps: ["180° = π rad"]),
            Question(id: "trig.rad.q2",
                     prompt: "Convert 90° to radians. In terms of π.", math: nil,
                     kind: .freeAnswer(accepted: ["pi/2", "π/2"]),
                     hint: "Half of 180°.",
                     solutionSteps: ["90° = 180°/2 = π/2"]),
            Question(id: "trig.rad.q3",
                     prompt: "2π radians equals:", math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "90°", math: nil),
                        .init(label: "180°", math: nil),
                        .init(label: "270°", math: nil),
                        .init(label: "360°", math: nil),
                     ], correctIndex: 3),
                     hint: "A full revolution.",
                     solutionSteps: ["2π rad = one full turn = 360°"]),
            Question(id: "trig.rad.q4",
                     prompt: "Convert π/3 radians to degrees.", math: nil,
                     kind: .freeAnswer(accepted: ["60", "60°"]),
                     hint: "Multiply by 180/π.",
                     solutionSteps: ["(π/3) · (180/π) = 180/3 = 60°"]),
            Question(id: "trig.rad.q5",
                     prompt: "True or false: π radians is a straight angle.", math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "π = 180°.",
                     solutionSteps: ["π rad = 180° = a straight angle"]),
        ]
    )

    static let lawOfSinesCosines = Lesson(
        id: "trig.laws",
        title: "Law of Sines & Cosines",
        intro: "Two laws extend trigonometry to any triangle — not just right ones.",
        formulas: [
            Formula(key: "trig.laws.f1",
                    name: "Law of sines",
                    math: "{var:a}/sin {var:A} = {var:b}/sin {var:B} = {var:c}/sin {var:C}",
                    explanation: "Each side over the sine of its opposite angle."),
            Formula(key: "trig.laws.f2",
                    name: "Law of cosines",
                    math: "{var:c}{sup:^2} = {var:a}{sup:^2} + {var:b}{sup:^2} − 2{var:a}{var:b} cos {var:C}",
                    explanation: "A generalized Pythagorean theorem."),
        ],
        questions: [
            Question(id: "trig.laws.q1",
                     prompt: "The law of cosines reduces to the Pythagorean theorem when the angle is:",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "0°", math: nil),
                        .init(label: "45°", math: nil),
                        .init(label: "90°", math: nil),
                        .init(label: "180°", math: nil),
                     ], correctIndex: 2),
                     hint: "Which angle makes the cosine term vanish?",
                     solutionSteps: ["cos 90° = 0", "c² = a² + b² − 0 = a² + b²"]),
            Question(id: "trig.laws.q2",
                     prompt: "True or false: the law of sines relates each side to the sine of its opposite angle.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "Read the formula.",
                     solutionSteps: ["a/sin A = b/sin B = c/sin C"]),
            Question(id: "trig.laws.q3",
                     prompt: "In c² = a² + b² − 2ab·cos C, if C = 90°, then cos C =", math: nil,
                     kind: .freeAnswer(accepted: ["0"]),
                     hint: "Cosine of a right angle.",
                     solutionSteps: ["cos 90° = 0"]),
            Question(id: "trig.laws.q4",
                     prompt: "You know two angles and one side of a triangle. Which law fits best?",
                     math: nil,
                     kind: .multipleChoice(options: [
                        .init(label: "Law of sines", math: nil),
                        .init(label: "Law of cosines", math: nil),
                        .init(label: "Pythagorean theorem", math: nil),
                        .init(label: "None of these", math: nil),
                     ], correctIndex: 0),
                     hint: "Angles paired with opposite sides.",
                     solutionSteps: ["Two angles + a side → law of sines"]),
            Question(id: "trig.laws.q5",
                     prompt: "True or false: the law of cosines can find a side from two sides and the angle between them.",
                     math: nil,
                     kind: .trueFalse(answer: true),
                     hint: "That's the 'SAS' case.",
                     solutionSteps: ["Given a, b, and C, the law of cosines gives c"]),
        ]
    )

    // MARK: - All topics

    static let topics: [Topic] = [
        Topic(id: "prealgebra",
              title: "Pre-Algebra",
              subtitle: "Fractions, percents, basics",
              icon: "number",
              color: Palette.stats,
              lessons: [preAlgFractions, preAlgPercents, preAlgOrder, preAlgNegatives,
                        preAlgDecimals, preAlgRatios, preAlgRoots]),
        Topic(id: "algebra",
              title: "Algebra",
              subtitle: "Equations & expressions",
              icon: "function",
              color: Palette.algebra,
              lessons: [linearEquations, quadratics, exponents, logarithms, factoring,
                        linesAndSlope, inequalities, systems, polynomials, algFunctions]),
        Topic(id: "calculus",
              title: "Calculus",
              subtitle: "Change & accumulation",
              icon: "chart.xyaxis.line",
              color: Palette.calculus,
              lessons: [limits, derivatives, integrals, chainRule,
                        productQuotient, definiteIntegrals, calcApplications]),
        Topic(id: "geometry",
              title: "Geometry",
              subtitle: "Shapes & distance",
              icon: "triangle",
              color: Palette.geometry,
              lessons: [pythagoras, circles, trianglesArea, volumes,
                        angles, quadrilaterals, geoSurfaceArea]),
        Topic(id: "trig",
              title: "Trigonometry",
              subtitle: "Angles & ratios",
              icon: "waveform.path",
              color: Palette.trig,
              lessons: [trigBasics, unitCircle, trigIdentities, radians, lawOfSinesCosines]),
    ]
}
